name: CI Workflow

on:
  push:
    branches: [fix/#3]  
  pull_request:
    branches: [main]

jobs:
  unit-functional-tests:
    name: Unit & Functional Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: env.yml
          auto-activate-base: false
          activate-environment: fsds-env

      - name: Install package in dev mode
        shell: bash -l {0}
        run: pip install -e .

      - name: Run pytest
        shell: bash -l {0}
        run: pytest tests/
        env:
          PYTHONPATH: "."

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: unit-functional-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: env.yml
          auto-activate-base: false
          activate-environment: fsds-env

      - name: Install tree tool
        run: sudo apt-get install -y tree

      - name: Tree before build
        run: tree -L 2

      - name: Build the package
        shell: bash -l {0}
        run: |
          pip install build
          python -m build

      - name: Tree after build
        run: tree -L 2

      - name: Upload dist and env
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            env.yml

  install:
    name: Install & Smoke Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./downloaded

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: ./downloaded/env.yml
          auto-activate-base: false
          activate-environment: fsds-env

      - name: Install built package
        shell: bash -l {0}
        run: |
          pip install downloaded/dist/*.whl
          
      - name: Create mlruns directory
        run: mkdir -p ./mlruns

      - name: Run workflow scripts (log to console)
        shell: bash -l {0}
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
        run: |
          echo "Running workflow scripts with timestamp logs"
          python scripts/ingest_data.py --output_folder outputs/data
          python scripts/train.py --output_folder outputs/model --input_folder outputs/data
          python scripts/score.py --model_folder outputs/model --dataset_folder outputs/data --output_folder outputs/metric
