name: CI Workflow

on:
  push:
    branches: [fix/#1]  # Change to 'main' for production
  pull_request:
    branches: [main]

jobs:
  style-test:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: env.yml
          auto-activate-base: false
          activate-environment: fsds-env

      - name: Run isort
        run: isort . --check --diff

      - name: Run black
        run: black . --check --diff

      - name: Run flake8
        run: flake8 .

  unit-functional-tests:
    name: Unit & Functional Tests
    runs-on: ubuntu-latest
    needs: style-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: env.yml
          auto-activate-base: false
          activate-environment: fsds-env

      - name: Install package in dev mode
        run: |
          pip install -e .

      - name: Run pytest
        run: pytest tests/
        env:
          PYTHONPATH: "."

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: unit-functional-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: env.yml
          auto-activate-base: false
          activate-environment: fsds-env

      - name: Install tree tool
        run: sudo apt-get install -y tree

      - name: Tree before build
        run: tree -L 2

      - name: Build the package
        run: |
          pip install build
          python -m build

      - name: Tree after build
        run: tree -L 2

      - name: Upload dist and env
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            dist/
            env.yml

  install:
    name: Install & Smoke Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./downloaded

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: ./downloaded/env.yml
          auto-activate-base: false
          activate-environment: fsds-env

      - name: Install built package
        run: |
          pip install downloaded/dist/*.whl

      - name: Run workflow scripts (log to console)
        run: |
          echo "Running workflow scripts with timestamp logs"
          python scripts/ingest_script.py --output_folder datasets/scripts
          python scripts/train.py --output_folder datasets/models --input_folder datasets/scripts/
          python scripts/score.py --model_folder datasets/models/ --dataset_folder datasets/scripts/ --output_folder datasets/results
