name: Pull and Run Docker Images

on:
    workflow_dispatch:

jobs:
    pull-and-run-ACR:
        name: RUN ACR
        runs-on: ubuntu-latest

        steps:
            - name: Log in to Azure Container Registry
              run: |
                echo "${{ secrets.ACR_PASSCODE }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
            
            - name: Pulling Docker image from ACR
              run: docker pull ${{secrets.ACR_NAME}}.azurecr.io/fsds-image:lts
            
            - name: Running Docker container
              run: docker run -d --name housing-model -p 8080:80 ${{secrets.ACR_NAME}}.azurecr.io/fsds-image:lts

            - name: Checking active container
              run: docker ps
            